@MSOC.Backend_HostAddress = http://localhost:5246

GET {{MSOC.Backend_HostAddress}}/api/healthcheck
Content-Type: text/plain

###

POST {{MSOC.Backend_HostAddress}}/api/player/query
Accept: application/json
Content-Type: application/json

{
  "friendCode": 1337
}

###

POST {{MSOC.Backend_HostAddress}}/api/player/query
Accept: application/json
Content-Type: application/json

{
  "friendCode": 8069933165057
}

###



